# Generated by Django 2.1.7 on 2019-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(default='describe the project here', max_length=500),
        ),
    ]
