# Generated by Django 2.1.7 on 2019-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='questions',
        ),
        migrations.AddField(
            model_name='polls',
            name='questionFive',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='polls',
            name='questionFour',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='polls',
            name='questionOne',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='polls',
            name='questionThree',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AddField(
            model_name='polls',
            name='questionTwo',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
    ]
