# Generated by Django 2.1.7 on 2019-04-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDescription',
            field=models.CharField(max_length=500),
        ),
    ]
