# Generated by Django 2.1.7 on 2019-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190320_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/pics/default.png', upload_to='pics'),
        ),
    ]
