# Generated by Django 2.1.7 on 2019-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190419_1304'),
        ('users', '0003_auto_20190417_1748'),
    ]

    operations = [
    ]
