# Generated by Django 2.1.7 on 2019-03-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pics/default.png', upload_to='pics/'),
        ),
    ]
