# Generated by Django 2.1.7 on 2019-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20190419_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userDescription',
            field=models.CharField(default='tell us about yourself', max_length=500),
        ),
        migrations.AlterField(
            model_name='polls',
            name='questionFive',
            field=models.CharField(default='Enter a Question', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='questionFour',
            field=models.CharField(default='Enter a Question', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='questionOne',
            field=models.CharField(default='Enter a Question', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='questionThree',
            field=models.CharField(default='Enter a Question', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='questionTwo',
            field=models.CharField(default='Enter a Question', max_length=120),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.CharField(default='Enter a Title for your Poll', max_length=120),
        ),
    ]
