# Generated by Django 2.1.7 on 2019-04-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190420_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('members_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='userDescription',
            field=models.CharField(default='tell us about yourself', max_length=500, verbose_name='User Description'),
        ),
        migrations.AddField(
            model_name='members',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='members',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
    ]
