# Generated by Django 2.1.7 on 2019-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(default='testuser__', max_length=100),
        ),
    ]
