# Generated by Django 2.1.7 on 2019-03-22 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dateTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
