# Generated by Django 2.1.7 on 2019-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_project_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete='CASCADE', to='users.Profile'),
        ),
    ]
