# Generated by Django 2.1.7 on 2019-04-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_polls_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
