# Generated by Django 2.1.7 on 2019-04-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190323_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='textArea',
            field=models.TextField(default='add info / planning here', max_length=10000),
        ),
        migrations.AddField(
            model_name='links',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
        migrations.AddField(
            model_name='files',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
    ]
