# Generated by Django 2.1.7 on 2019-04-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190420_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='creator',
            field=models.ForeignKey(default='Not Logged IN', on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
