# Generated by Django 2.1.7 on 2019-04-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190415_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('polls_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('questions', models.CharField(max_length=120)),
            ],
        ),
    ]
